import type { Metadata } from "next";
import { inter } from "@/src/app/fonts";
import "./globals.css";
import { AuthProvider } from "../context/authContext";
import ToastProvider from "../context/ToastContext";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="pt-br">
        <body className={inter.className}>
          <ToastProvider>
            {children}
          </ToastProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
