version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - 80:3000
    depends_on:
      - backend
      - mariadb
    volumes:
      - ./frontend/src:/app/src
    command: npm run dev

  backend:
    build: ./backend
    depends_on:
      - mariadb
    volumes:
      - ./backend/src:/app/src
    command: npm run start:dev
    ports:
      - 3000:3000

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gcid
      - MYSQL_USER=gcid
      - MYSQL_PASSWORD=gcid
    ports:
      - 33069:3306

  redis:
    image: redis
    ports:
      - 6379:6379
