import { AuthProvider } from "@/src/context/authContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function NestedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <html lang="pt-br" className="h-screen">
      <body className='h-screen'>{children}</body>
    </html>
    </AuthProvider>
  );
}
